name: dev.yml
trigger: none

pool: knew-pool

variables: 
  WORK_DIR: '$(System.DefaultWorkingDirectory)/environment/dev'
  

stages:
  - stage: precommit
    displayName: Precommit Stage
    jobs:
    - job: terraforminit
      displayName: Terraform INIT & Validate
      steps:
      - task: TerraformInstaller@1
        inputs:
          terraformVersion: '1.14.3'
      - task: TerraformTask@5
        displayName: Terraform INIT
        inputs:
          provider: 'azurerm'
          command: 'init'
          workingDirectory: '$(WORK_DIR)'
          backendServiceArm: 'kash-connection'
          backendAzureRmStorageAccountName: 'kashsa433490'
          backendAzureRmContainerName: 'kscont'
          backendAzureRmKey: 'dev.terraform.tfstate'

      - task: TerraformTask@5
        displayName: Terraform Validate
        inputs:
          provider: 'azurerm'
          command: 'validate'
          workingDirectory: '$(WORK_DIR)'

      - task: TerraformTask@5
        displayName: Terraform FMT
        inputs:
          provider: 'azurerm'
          command: 'custom'
          workingDirectory: '$(WORK_DIR)'
          outputTo: 'console'
          customCommand: 'fmt'
          environmentServiceNameAzureRM: 'kash-connection'

  - stage: scanning
    displayName: Scanning Stage
    jobs:
      - job: tfsec
        displayName: TFsec
        pool: knew-pool
        steps:
        - task: tfsec@1 
          displayName: Terraform TFsec
          inputs:
            version: 'v1.26.0'
            dir: '$(WORK_DIR)'
            softFail: true
      
      - job: tflint
        displayName: TFlint
        pool: knew-pool
        steps:
        # - task: PowerShell@2
        - powershell: |
            Write-Host "Checking TFLint version..."
            tflint --version
            

        # Run TFLint
        - powershell: |
            Write-Host "Running TFLint..."
            Set-Location "$(System.DefaultWorkingDirectory)/environment/dev"
            tflint --init
            tflint --recursive --enable-rule=terraform_required_providers --force
            


  - stage: plan
    dependsOn:
      - precommit
      - scanning
    displayName: Plan and Review Stage
    jobs:
      - job: terraformplan
        displayName: Terraform Plan
        pool: knew-pool
        steps:
        - task: TerraformInstaller@1
          inputs:
            terraformVersion: '1.14.3'
        - task: TerraformTask@5
          
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(System.DefaultWorkingDirectory)/environment/dev'
            backendServiceArm: 'kash-connection'
            backendAzureRmStorageAccountName: 'kashsa433490'
            backendAzureRmContainerName: 'kscont'
            backendAzureRmKey: 'dev.terraform.tfstate'

        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'plan'
            workingDirectory: '$(System.DefaultWorkingDirectory)/environment/dev'
            environmentServiceNameAzureRM: 'kash-connection'

  - stage: infracostStage
    dependsOn: 
      - precommit
      - scanning
      - plan
    displayName: Cost and Impact Assesment Stage
    jobs:
      - job: InfraCost
        displayName: InfraCost
        steps:
        - task: InfracostSetup@2
          inputs:
            apiKey: 'ico-HcTDRcRFOiy1HodRPi3nqK3fyEMRvzCc'
            version: '0.10.x'
        - task: PowerShell@2
          inputs:
            targetType: 'inline'
            script: 'infracost breakdown --path=$(System.DefaultWorkingDirectory)/environment/dev'
            workingDirectory: '$(WORK_DIR)'
        

  - stage: approval
    dependsOn: 
      - plan
      - infracostStage
    displayName: Approval Stage
    jobs:
      - job: manualapproval
        displayName: Manual Approval
        pool: server
        steps:
        - task: ManualValidation@1
          inputs:
            notifyUsers: 'kashifshivani.exness@gmail.com'

  - stage: apply  
    dependsOn: approval
    displayName: Apply Stage
    jobs:
      - job: apply
        displayName: Apply
        pool: knew-pool
        steps:
        - task: TerraformInstaller@1
          inputs:
            terraformVersion: '1.14.3'
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(System.DefaultWorkingDirectory)/environment/dev'
            backendServiceArm: 'kash-connection'
            backendAzureRmStorageAccountName: 'kashsa433490'
            backendAzureRmContainerName: 'kscont'
            backendAzureRmKey: 'dev.terraform.tfstate'
        
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'apply'
            workingDirectory: '$(System.DefaultWorkingDirectory)/environment/dev'
            environmentServiceNameAzureRM: 'kash-connection'

